### ISSUE TITLE
"Mark homework 1, exercises 3 of Melody-Sain"

### ISSUE THREAD

**Issue by melpsain** [melpsain/stat679work#2]
## Homework 1 part 3 Submission 2

@cecileane  I am submitting my homwork1 exercise 3. The link below is the link to my commit. 
https://github.com/melpsain/stat679work/commit/52476390a23e71f91c2b6dcd12e27baf201a0d8a

**Comment by cecileane** [comment]
Thanks Melody! This is my way of asking Chelsey (@ChelseyGreen) and TJ (@WangTJ) to try your script and provide feedback on it.

**Comment by ChelseyGreen** [comment]
Hi Melody, I've included some feedback below on your code and files for exercise 3. 
(1)You have very clear and thorough readme files that make it easy for me to navigate through your files and know how and where to run your scripts. You also have very good commenting throughout your code that makes it easier for me to understand what you are doing. 

Some comments on your actual code:
(2) Echoing the variables to the screen can be helpful for debugging and to show the progress of the script. I can see some users preferring not to see that however, so perhaps you could add a parameter and some if statements before your echo commands so they could be turned off/on more easily. 
(3) Your code runs as desired and creates the CSV file we'd like. You may consider having your code put the resulting CSV file in another "analysis" directory or something of the like.
(4) The combinations of sed, grep, and cut you used required a great deal of knowledge applied together!  You can actually use the sed command to find any string in the file so you don't need to use as many piped commands- like you did for the loglik variable. I can show you this sometime for some of the other variables if you'd like.
(5) I really like how you only returned the value before the period for loglik. I returned all of it and then striped the part after the decimal off-- your way is more efficient!
(6) While your loops through the loglik values absolutely work, you could make your code more compact by nesting the if statements within one for/do loop.  First check if loglik lt 3460, if so update count and then check if loglik lt 3450, if so update count, etc. Currently you loop through loglik 3 different times which isn't a huge deal with how many loglik values we have, but it could hurt performance if we have a ton of values. 

Let me know if you have any questions about my feedback or suggestions. Thanks for letting me look at your code!
Chelsey

**Comment by WangTJ** [comment]
Hi Melody,

It's informative to show the structure of repository in the Readme file. The arrangement of files are very clear and professional, I like you separate the output and scripts in different subdirectories. I think it will be better if you edit the README file for subdirectory **hw1**, its format is not as good as other markdown files in your work.

And your comments in the code are rich and clear. It helps others read your code easily. 
In your code, I appreciate your use of "sed", it's clear. 

In the counting part, you put the counting of 3460, 3450 and 3440 in three separate loops and your indentations in this part are not well-organized. I agree with Chelsey's comment that you can put them in one big loop and it will be more brilliant if you nest the if statement together.

Overall, you do this work brilliantly and I think I can learn something from your way.

TJ
